// Calendário Maternal 2025
(function() {
  const calendarDataMaternal = {
    months: [
      {
        name: "Janeiro",
        days: [
          { date: 1, events: [{ type: "feriado", text: "Ano Novo" }] },
          { date: 2, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 3, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 4, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 5, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 6, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 7, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 8, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 9, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 10, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 11, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 12, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 13, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 14, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 15, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 16, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 17, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 18, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 19, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 20, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 21, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 22, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 23, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 24, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 25, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 26, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 27, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 28, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 29, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 30, events: [{ type: "ferias", text: "Férias Escolares" }] },
          { date: 31, events: [{ type: "ferias", text: "Férias Escolares" }] },
        ],
      },
      {
        name: "Fevereiro",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          {
            date: 3,
            events: [{ type: "pedagogica", text: "Semana Pedagógica" }],
          },
          {
            date: 4,
            events: [{ type: "pedagogica", text: "Semana Pedagógica" }],
          },
          {
            date: 5,
            events: [{ type: "pedagogica", text: "Semana Pedagógica" }],
          },
          {
            date: 6,
            events: [{ type: "pedagogica", text: "Semana Pedagógica" }],
          },
          {
            date: 7,
            events: [{ type: "pedagogica", text: "Semana Pedagógica" }],
          },
          { date: 8, events: [{ type: "reuniao", text: "Reunião de Pais" }] },
          { date: 9, events: [] },
          { date: 10, events: [{ type: "inicio", text: "Início das Aulas" }] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
        ],
      },
      {
        name: "Março",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [{ type: "feriado", text: "Feriado/Carnaval" }] },
          { date: 4, events: [{ type: "feriado", text: "Feriado/Carnaval" }] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          {
            date: 26,
            events: [{ type: "feriado", text: "Feriado/Emancipação Barueri" }],
          },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
          { date: 31, events: [] },
        ],
      },
      {
        name: "Abril",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [{ type: "feriado", text: "Endoenças" }] },
          { date: 18, events: [{ type: "feriado", text: "Sexta-feira Santa" }] },
          { date: 19, events: [] },
          { date: 20, events: [{ type: "feriado", text: "Páscoa" }] },
          { date: 21, events: [{ type: "feriado", text: "Tiradentes" }] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
        ],
      },
      {
        name: "Maio",
        days: [
          { date: 1, events: [{ type: "feriado", text: "Dia do Trabalho" }] },
          {
            date: 2,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 9, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
          { date: 31, events: [] },
        ],
      },
      {
        name: "Junho",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [{ type: "evento", text: "Festa Junina" }] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [{ type: "feriado", text: "Corpus Christi" }] },
          {
            date: 20,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          { date: 21, events: [] },
          { date: 22, events: [] },
          {
            date: 23,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          {
            date: 24,
            events: [{ type: "feriado", text: "Padroeiro São João Batista" }],
          },
          { date: 25, events: [] },
          { date: 26, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 27, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 29, events: [] },
          { date: 30, events: [] },
        ],
      },
      {
        name: "Julho",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [{ type: "reuniao", text: "Reunião de Pais" }] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 8, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 9, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 10, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 11, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 12, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 13, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 14, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 15, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 16, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 17, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 18, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 19, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 20, events: [{ type: "ferias", text: "Recesso Escolar" }] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
          { date: 31, events: [] },
        ],
      },
      {
        name: "Agosto",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
          { date: 31, events: [] },
        ],
      },
      {
        name: "Setembro",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [{ type: "evento", text: "Civico Militar" }] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 26, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
        ],
      },
      {
        name: "Outubro",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [{ type: "reuniao", text: "Reunião de Pais" }] },
          { date: 5, events: [] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 12, events: [] },
          { date: 11, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          {
            date: 15,
            events: [{ type: "Dia sem Expediente", text: "Dia do Professor" }],
          },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          {
            date: 27,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          {
            date: 28,
            events: [{ type: "feriado", text: "Funcionário Publico" }],
          },
          { date: 29, events: [] },
          { date: 30, events: [] },
          { date: 31, events: [] },
        ],
      },
      {
        name: "Novembro",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [] },
          { date: 5, events: [] },
          { date: 6, events: [{ type: "reuniao", text: "Reunião de Pais" }] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          {
            date: 15,
            events: [{ type: "feriado", text: "Proclamação da República" }],
          },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [{ type: "feriado", text: "Consciencia Negra" }] },
          {
            date: 21,
            events: [{ type: "feriado", text: "Nossa Senhora da Escada" }],
          },
          { date: 22, events: [] },
          { date: 23, events: [] },
          { date: 24, events: [] },
          { date: 25, events: [] },
          { date: 26, events: [] },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
        ],
      },
      {
        name: "Dezembro",
        days: [
          { date: 1, events: [] },
          { date: 2, events: [] },
          { date: 3, events: [] },
          { date: 4, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 5, events: [{ type: "evento", text: "Conselho de Classe" }] },
          { date: 6, events: [] },
          { date: 7, events: [] },
          { date: 8, events: [] },
          { date: 9, events: [] },
          { date: 10, events: [] },
          { date: 11, events: [] },
          { date: 12, events: [] },
          { date: 13, events: [] },
          { date: 14, events: [] },
          { date: 15, events: [] },
          { date: 16, events: [] },
          { date: 17, events: [] },
          { date: 18, events: [] },
          { date: 19, events: [] },
          { date: 20, events: [] },
          { date: 21, events: [] },
          { date: 22, events: [] },
          { date: 23, events: [] },
          {
            date: 24,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          { date: 25, events: [] },
          {
            date: 26,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
          { date: 27, events: [] },
          { date: 28, events: [] },
          { date: 29, events: [] },
          { date: 30, events: [] },
          {
            date: 31,
            events: [{ type: "Dia sem Expediente", text: "Dia sem Expediente" }],
          },
        ],
      },
    ],
  };

  function initializeCalendarMaternal() {
    // Exemplo: renderizar calendário Maternal
    console.log('Inicializando calendário Maternal', calendarDataMaternal);
    // Aqui vai a lógica de renderização específica
  }

  // Inicialização automática ao carregar o script
  initializeCalendarMaternal();
})(); 