const schools = [
  {
    type: "EMEF",
    name: "Agenor Lino de Mattos - Dep.",
    phones: ["4198-3834"],
    ramal: [],
    whatsapp: "(11) 4198-3834",
    address: "R. Treze de Maio, 59",
    neighborhood: "Vila Universal",
    latitude: -23.5132,
    longitude: -46.8742,
    director: "Marcio Aparecido Lima",
    directorEmail: "marcio.lima@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Alcino Francisco de Souza - Prof.",
    phones: ["4194-6915", "4194-6876"],
    ramal: [],
    whatsapp: "(11) 4194-6915",
    address: "Av. Pres. Washington Luiz, 444",
    neighborhood: "Jardim Silveira",
    latitude: -23.5242,
    longitude: -46.8852,
    director: "Maria Celia Alves Carvalho Sanches",
    directorEmail: "maria.sanches@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Alexandrino da Silveira Bueno-Prof.",
    phones: ["4194-1330", "4162-0013"],
    ramal: [],
    whatsapp: "(11) 4194-1330",
    address: "Av. Brig. Manoel R. Jordão, 836",
    neighborhood: "Jardim Silveira",
    latitude: -23.5245,
    longitude: -46.8855,
    director: "Marcos Paes de Barros",
    directorEmail: "marcos.barros@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Alfredo do Carmo - Prof.",
    phones: ["4163-6957", "4163-6941"],
    ramal: [],
    whatsapp: "(11) 4163-6941",
    address: "R. Marta, 20",
    neighborhood: "Vila Nova",
    latitude: -23.535,
    longitude: -46.896,
    director: "Paula Regina Araujo de Azevedo Silva",
    directorEmail: "paula.azevedo@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Amador Aguiar",
    phones: ["4193-6573", "4688-1275", "4191-3689"],
    ramal: [],
    whatsapp: "(11) 4193-6573",
    address: "Rua Martins Fontes, 412",
    neighborhood: "Parque Imperial",
    latitude: -23.5305,
    longitude: -46.8915,
    director: "Adriana Cardoso do Nascimento",
    directorEmail: "adriana.nascimento@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Aristides da Costa e Silva-Prof.",
    phones: ["4198-1208", "4163-2831"],
    ramal: [],
    whatsapp: "(11) 4198-1208",
    address: "Av.Henrique Gonçalves Baptista, 1.097",
    neighborhood: "Jardim Belval",
    latitude: -23.514,
    longitude: -46.875,
    director: "Geovane Santos da Silva",
    directorEmail: "geovane.santos@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Armando Cavazza (EJA)",
    phones: ["4168-4296", "4161-6045"],
    ramal: [],
    whatsapp: "(11) 4168-4296",
    address: "R. São Paulo, 706",
    neighborhood: "Engenho Novo",
    latitude: -23.5125,
    longitude: -46.8735,
    director: "Fernanda Aparecida Moreno Moreti",
    directorEmail: "fernanda.moreti@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Bruno Tolaini",
    phones: ["4194-1325", "4194-6103"],
    ramal: [],
    whatsapp: "(11) 4194-1325",
    address: "Estrada das Pitas, 699",
    neighborhood: "Parque Viana",
    latitude: -23.5352,
    longitude: -46.8962,
    director: "Carla Luiza Alves Bezerra",
    directorEmail: "carla.bezerra@educbaruerisp.gov.br",
  },
  {
    type: "EMEF",
    name: "Carlos Osmarinho de Lima - Prof. (Compl.)",
    phones: ["4163-4047"],
    ramal: [],
    whatsapp: "(11) 4163-4047",
    address: "Rua das Margaridas, 182",
    neighborhood: "Jardim Flórida",
    latitude: -23.5172,
    longitude: -46.8782,
    director: "Marina de Andrade",
    directorEmail: "marina.andrade@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Dalva Fogaça - Prof.",
    phones: ["4194-0002", "4162-0016"],
    ramal: [],
    whatsapp: "(11) 4194-0002",
    address: "Av. Brig. Manoel R. Jordão, 1.127",
    neighborhood: "Jardim Silveira",
    latitude: -23.5247,
    longitude: -46.8857,
    director: "Ursula Gabriela Goss de Sena",
    directorEmail: "ursula.sena@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Deiró Felicio de Andrade- Rev",
    phones: ["4194-3602"],
    ramal: [],
    whatsapp: "(11) 4194-3602",
    address: "R. Piratininga, 103",
    neighborhood: "Jardim Paulista",
    latitude: -23.5225,
    longitude: -46.8835,
    director: "Lilian de Souza Albuquerque",
    directorEmail: "lilian.albuquerque@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Dorival Faria",
    phones: ["4161-6384", "4168-2037"],
    ramal: [],
    whatsapp: "(11) 4168-2037",
    address: "Rua Marte, 55",
    neighborhood: "Jardim Tupanci",
    latitude: -23.5367,
    longitude: -46.8977,
    director: "Daniel Felipe Cezario",
    directorEmail: "daniel.cezario@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Egídio Costa - Prof.",
    phones: ["4163-6064", "4163-5761"],
    ramal: [],
    whatsapp: "(11) 4163-6064",
    address: "R. Ponte de Pedras, 60",
    neighborhood: "Jardim Califórnia",
    latitude: -23.516,
    longitude: -46.877,
    director: "Graciellen Gomes da Silva",
    directorEmail: "graciellen.gomes@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Eizaburo Nomura - Prof",
    phones: ["4201-6786", "4201-6263"],
    ramal: [],
    whatsapp: "(11) 4201-6768",
    address: "Av Marginal Esquerda, 1.177",
    neighborhood: "Jardim Paulista",
    latitude: -23.5227,
    longitude: -46.8837,
    director: "Andre Luiz Alves Lima",
    directorEmail: "andre.lima@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Elizabeth Parminondi Romero",
    phones: ["4168-1072", "4168-1670"],
    ramal: [],
    whatsapp: "(11) 4168-1670",
    address: "Rua Iepê, 11",
    neighborhood: "Jardim Graziela",
    latitude: -23.518,
    longitude: -46.879,
    director: "Soraia Aparecida da Silva Subtil",
    directorEmail: "soraia.subtil@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Elvira Lefevre S. Nemer - Profª (EJA)",
    phones: ["4163-4925", "4163-4924"],
    ramal: [],
    whatsapp: "(11) 4163-4924",
    address: "Av.Henriqueta Mendes Guerra, 1.168",
    neighborhood: "Vila São João",
    latitude: -23.537,
    longitude: -46.898,
    director: "Jose Luiz Inacio",
    directorEmail: "jose.inacio@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Estevan Placêncio",
    phones: ["3164-1132"],
    ramal: [],
    whatsapp: "(11) 3164-1132",
    address: "Av. Arnaldo Rodrigues Bittencourt, 1428",
    neighborhood: "Nova Aldeinha",
    latitude: -23.5332,
    longitude: -46.8942,
    director: "Margareth Ferreira Rodrigues",
    directorEmail: "margareth.rodrigues@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Ezio Berzaghi",
    phones: ["4199-0864", "4199-0851"],
    ramal: [],
    whatsapp: "(11) 4199-0851",
    address: "Av.Henrique Gonçalves Baptista, 1.101",
    neighborhood: "Jardim Belval",
    latitude: -23.5142,
    longitude: -46.8752,
    director: "Renan Francisco de Souza",
    directorEmail: "renan.souza@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Fioravante Barletta",
    phones: ["4194-0701", "4201-7344"],
    ramal: ["660"],
    whatsapp: "(11) 4201-7345",
    address: "Via Taboão, 742",
    neighborhood: "Jardim Silveira",
    latitude: -23.525,
    longitude: -46.886,
    director: "Sergio Augusto da Silva",
    directorEmail: "sergio.silva@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Gilberto Florêncio-Prof.",
    phones: ["4163-1338", "4163-1557"],
    ramal: ["760", "761", "762", "763", "764", "765"],
    whatsapp: "(11) 4163-1338",
    address: "Rua Indonésia, 1101",
    neighborhood: "Jardim Reginalice",
    latitude: -23.5237,
    longitude: -46.8847,
    director: "Renata Aparecida de Lima",
    directorEmail: "renata.lima@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Ivani Maria Paes - Prof.ª",
    phones: ["4163-4109"],
    ramal: [],
    whatsapp: "(11) 4163-4109",
    address: "Rua Ivani Maria Paes, 21",
    neighborhood: "Jardim dos Camargos",
    latitude: -23.5165,
    longitude: -46.8775,
    director: "Pamela de Campos Santos Lima",
    directorEmail: "pamela.lima@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "João Carvalho de Lima",
    phones: ["4191-5736", "4689-1472", "4688-2064"],
    ramal: [],
    whatsapp: "(11) 4191-5736",
    address: "R. Mauro José da Silva Jangada, 325",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5202,
    longitude: -46.8812,
    director: "Wagner Jose dos Santos",
    directorEmail: "wagner.jose@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "João de Almeida Lemos",
    phones: ["4198-8992", "4163-1142"],
    ramal: [],
    whatsapp: "(11) 4198-8992",
    address: "R. Vitorino Calegare, 259",
    neighborhood: "Jardim Paraíso",
    latitude: -23.522,
    longitude: -46.883,
    director: "Renata Patricia de Farias",
    directorEmail: "renata.farias@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "João Tiburcio Silva Filho",
    phones: ["4168-5707", "4168-5238"],
    ramal: [],
    whatsapp: "(11) 4168-5707",
    address: "R. Cambuci, 189",
    neighborhood: "Chácaras Marco",
    latitude: -23.512,
    longitude: -46.873,
    director: "Maria Aparecida Franco",
    directorEmail: "maria.franco@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Jorge Augusto de Camargo-Prof.",
    phones: ["4168-4219"],
    ramal: ["700"],
    whatsapp: "(11) 4168-4219",
    address: "Rua Cafelândia, 924",
    neighborhood: "Engenho Novo",
    latitude: -23.5127,
    longitude: -46.8737,
    director: "Alexandro Cardoso",
    directorEmail: "alexandro.cardoso@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "José Domingos da Silveira - Prof.",
    phones: ["4191-2577", "4689-1443"],
    ramal: ["780"],
    whatsapp: "(11) 4191-2577",
    address: "Rua São Vicente de Paula, 100",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5205,
    longitude: -46.8815,
    director: "Fernando Laiola",
    directorEmail: "fernando.laiola@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "José Leandro de Barros Pimentel",
    phones: ["4194-0202", "4201-2461"],
    ramal: [],
    whatsapp: "(11) 4194-0202",
    address: "R Paiaguas, 62",
    neighborhood: "Jardim Silveira",
    latitude: -23.5252,
    longitude: -46.8862,
    director: "Marcia Maria de Souza",
    directorEmail: "marcia.ssilva@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Julio Gomes Camisão",
    phones: ["4191-3077", "4688-2078"],
    ramal: ["820", "822"],
    whatsapp: "(11) 91300-1829",
    address: "Rua Padre Cícero Romão Batista, 269",
    neighborhood: "Parque Imperial",
    latitude: -23.5307,
    longitude: -46.8917,
    director: "Teder Roberto Sacoman",
    directorEmail: "teder.sacoman@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Levy Gonçalves de Oliveira",
    phones: ["4191-2262", "4688-2361"],
    ramal: [],
    whatsapp: "(11) 4191-2261",
    address: "R.Renilde de Almeida, 400",
    neighborhood: "Parque Imperial",
    latitude: -23.531,
    longitude: -46.892,
    director: "Fabiana Pansarin de Barcelos",
    directorEmail: "fabiana.barcelos@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Luiz de Oliveira Andrade - Pe",
    phones: ["4168-3217", "4168-3605"],
    ramal: ["860", "861", "862"],
    whatsapp: "(11) 4168-3217",
    address: "R. Maria Helena, 191",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.5355,
    longitude: -46.8965,
    director: "Antonio Sergio Ferreira",
    directorEmail: "antonio.ferreira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Margarida Maria Maciel",
    phones: ["4201-5597", "4168-9059", "4201-5573"],
    ramal: ["880"],
    whatsapp: "(11) 4201-5597",
    address: "R. Adonilson Alves Ferreira, 205",
    neighborhood: "Vale do Sol",
    latitude: -23.5342,
    longitude: -46.8952,
    director: "Carlos Alberto Fernandes de Siqueira",
    directorEmail: "carlos.siqueira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Maria Elisa B. C. Chaluppe-Profª",
    phones: ["4198-7900", "4163-7248"],
    ramal: ["900", "901", "902"],
    whatsapp: "(11) 4198-7900",
    address: "R. Sergio Berringer, 125",
    neighborhood: "Vila São Luiz (Centro)",
    latitude: -23.5372,
    longitude: -46.8982,
    director: "Cassia Aparecida Alves Diniz",
    directorEmail: "cassia.diniz@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Maria Meduneckas - Prof.ª (Complexo)",
    phones: ["4194-6099"],
    ramal: [],
    whatsapp: "(11)4194-6099",
    address: "Av. Pres. Washington Luiz, 600",
    neighborhood: "Jardim Silveira",
    latitude: -23.5255,
    longitude: -46.8865,
    director: "Silvio Pereira da Silva",
    directorEmail: "silvio.silva@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Marlene Pereira Santiago - Profª",
    phones: ["4191-2225", "4191-2071"],
    ramal: [],
    whatsapp: "(11) 4191-2225",
    address: "Rua Tomé de Souza, 259",
    neighborhood: "Parque Imperial",
    latitude: -23.5312,
    longitude: -46.8922,
    director: "Edvanio Caetano da Silva",
    directorEmail: "edvanio.silva@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Naly Benedicta B. C. Mancini- Profª",
    phones: ["4198-5999", "4163-4719"],
    ramal: [],
    whatsapp: "(11) 4163-4719",
    address: "Rua Princesa Isabel, 145",
    neighborhood: "Jardim Belval",
    latitude: -23.5147,
    longitude: -46.8757,
    director: "Maria Elizabeth de Oliveira Borges",
    directorEmail: "mariaelizabeth.borges@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Nestor de Camargo -Pref.",
    phones: ["4191-8994", "4191-8973"],
    ramal: ["980"],
    whatsapp: "(11) 4191-8973",
    address: "Rua Abelardo Luz, 86",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5207,
    longitude: -46.8817,
    director: "Fernando Abreu Pestana",
    directorEmail: "fernando.pestana@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Onofra da Silva",
    phones: ["4201-1781", "4194-6688"],
    ramal: [],
    whatsapp: "(11) 4194-6688",
    address: "Estrada dos Pinheiros, 1.450",
    neighborhood: "Jardim Paulista",
    latitude: -23.523,
    longitude: -46.884,
    director: "Henrique Arakem Martins",
    directorEmail: "henrique.martins@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Osvaldo Batista Pereira (EJA)",
    phones: ["4194-6588", "4194-6375"],
    ramal: ["1840", "1841"],
    whatsapp: "(11) 4194-6588",
    address: "R. Nelly Masieiro Fernandes, 110",
    neighborhood: "Recanto Phrynea",
    latitude: -23.532,
    longitude: -46.893,
    director: "Olavo Vinicius Barbosa de Almeida",
    directorEmail: "olavo.almeida@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Raposo Tavares (EJA)",
    phones: ["4163-1605"],
    ramal: [],
    whatsapp: "(11) 4163-1605",
    address: "R. Silveira, 15",
    neighborhood: "Vila Boa Vista",
    latitude: -23.536,
    longitude: -46.897,
    director: "Claudio Francisco Barbosa Ventura",
    directorEmail: "claudio.ventura@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Renato Rosa",
    phones: ["4194-1289", "4194-1310"],
    ramal: ["970"],
    whatsapp: "(11) 4194-1310",
    address: "Estrada das Pitas, 799",
    neighborhood: "Parque Viana",
    latitude: -23.5357,
    longitude: -46.8967,
    director: "Lilieyd Guimaraes Santos",
    directorEmail: "lilieyd.santos@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Rita de Jesus (EJA)",
    phones: ["4208-5561", "4208-5562"],
    ramal: ["1080", "1081"],
    whatsapp: "(11) 4208-5561",
    address: "Rua Duarte da Costa, 143",
    neighborhood: "Parque Imperial",
    latitude: -23.5315,
    longitude: -46.8925,
    director: "Nidia Barroso de Carvalho Oliveira",
    directorEmail: "nidia.oliveira@professor.barueri.br",
  },
  {
    type: "EMEF",
    name: "Roberto Luiz de Araujo Brandão",
    phones: ["4201-2562"],
    ramal: ["1130", "1133"],
    whatsapp: "(11) 4201-2562",
    address: "Av. Anibal Correia, 2.363",
    neighborhood: "Parque Viana",
    latitude: -23.5362,
    longitude: -46.8972,
    director: "Agrailton da Silva Palmeira",
    directorEmail: "agrailton.palmeira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Sandro Luiz Braga",
    phones: ["4161-2256", "4161-5413"],
    ramal: ["91120", "91121", "91122"],
    whatsapp: "(11) 4161-2256",
    address: "Rua Nina, 300",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.5365,
    longitude: -46.8975,
    director: "Patricia Monteiro",
    directorEmail: "patricia.monteiro@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Sidney Santucci - Prof",
    phones: ["4162-4733"],
    ramal: [],
    whatsapp: "(11) 4162-4733",
    address: "Av. São Fernando, 565",
    neighborhood: "Jardim Julio",
    latitude: -23.517,
    longitude: -46.878,
    director: "Cristina Madalena Pereira",
    directorEmail: "cristina.pereira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEF",
    name: "Suzete da Costa e Silva Mariano",
    phones: ["4194-4667"],
    ramal: [],
    whatsapp: "(11) 4194-4667",
    address: "Av. Giovani Attílio Tolaine, s/nº",
    neighborhood: "Jd. Maria Helena",
    latitude: -23.519,
    longitude: -46.88,
    director: "Rodrigo Vicentin Raposo",
    directorEmail: "rodrigo.raposo@professor.barueri.br",
  },
  {
    type: "EMEIEF",
    name: "Anna Irene Mazaro de Freitas",
    phones: ["5570-2038 - EMEF", "5570-2036 - EMEI"],
    ramal: [],
    whatsapp: "940277376",
    address: "Estrada dos Pinheiros, 198",
    neighborhood: "Parque Viana",
    latitude: -23.536,
    longitude: -46.897,
    director: "Ana Paula de Jesus Pereira Araujo",
    directorEmail: "ana.araujo@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Benedito Adherbal Farbo",
    phones: ["4194-3597", "4201-6616"],
    ramal: ["1180"],
    whatsapp: "(11) 4194-3597",
    address: "Rua Nilo, 99",
    neighborhood: "Vale do Sol",
    latitude: -23.534,
    longitude: -46.895,
    director: "Sandra Aparecida Nogueira",
    directorEmail: "sandra.nogueira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Elisabet Titto - Ver.",
    phones: ["5570-2021"],
    ramal: ["91321", "91322"],
    whatsapp: "(11) 5570-2021",
    address: "Rua Ricardo Peagno, 52",
    neighborhood: "Jardim Belval",
    latitude: -23.515,
    longitude: -46.876,
    director: "Aline Angelica Lima Nonato",
    directorEmail: "aline.nonato@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Eneias Raimundo da Silva - Prof.",
    phones: ["4198-7855 - ", "4706-1056"],
    ramal: ["1050", "1070", "1071", "1072", "1073", "1074"],
    whatsapp: "(11) 4198-7855",
    address: "Est. Dr. Cicero Borges Moraes, 2.371",
    neighborhood: "Bairro dos Altos",
    latitude: -23.5115,
    longitude: -46.8723,
    director: "Fernando Grandeza",
    directorEmail: "fernando.grandeza@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Francisco Zacarioto",
    phones: ["4552-6932"],
    ramal: [],
    whatsapp: "(11) 4552-6932",
    address: "Rua Ipanema, 420",
    neighborhood: "Jardim Maria Helena",
    latitude: -23.5192,
    longitude: -46.8802,
    director: "Fernanda Vieira da Silva",
    directorEmail: "fernanda.vsilva@professor.barueri.br",
  },
  {
    type: "EMEIEF",
    name: "José Emidio de Aguiar",
    phones: ["4163-2031", "4163-2126"],
    ramal: ["1380"],
    whatsapp: "(11) 4163-2126",
    address: "R. Augusta, 198",
    neighborhood: "Jardim Maria Tereza",
    latitude: -23.4988136,
    longitude: -46.8732441,
    director: "Carlos Roberto Coimbra de Oliveira",
    directorEmail: "carlos.oliveira@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Taro Mizutori - Prof.",
    phones: ["4161-6499", "4168-3238"],
    ramal: [],
    whatsapp: "(11) 4161-6499",
    address: "Rua Tailândia, 20",
    neighborhood: "Jardim Mutinga",
    latitude: -23.521,
    longitude: -46.882,
    director: "Katia Cristina Gomes da Rocha",
    directorEmail: "katia.rocha@educbarueri.sp.gov.br",
  },
  {
    type: "EMEIEF",
    name: "Zilda de M. B. E. G. Arnoni-Profª",
    phones: ["4162-4318", "4162-4211"],
    ramal: [],
    whatsapp: "(11) 4162-4211",
    address: "Rua João Evangelista de A. Costa, 1.250",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.535,
    longitude: -46.896,
    director: "Simone Martins Marques de Queiroz",
    directorEmail: "simone.queiroz@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Adagisa M. A. F. de Lima - Prof.ª",
    phones: ["4163-7186", "4163-2415"],
    ramal: [],
    whatsapp: "(11) 4163-7186",
    address: "R. Cap. Anacleto, 137",
    neighborhood: "Centro",
    latitude: -23.5135,
    longitude: -46.8745,
    director: "Sandra Regina da Silva",
    directorEmail: "sandra.rsilva@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Amador Aguiar",
    phones: ["4193-2780", "4688-2195"],
    ramal: [],
    whatsapp: "(11) 4193-2780",
    address: "Rua Cândido Portinari, 40",
    neighborhood: "Vila São Silvestre",
    latitude: -23.5375,
    longitude: -46.8985,
    director: "Renata Cristiane Lopes",
    directorEmail: "renata.lopes@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Angela M. F. de Oliveira-Profª",
    phones: ["4161-4603", "4161-4552"],
    ramal: [],
    whatsapp: "(11) 4161-4603",
    address: "R. Mar Vermelho, 677",
    neighborhood: "Jardim Reginalice",
    latitude: -23.5242,
    longitude: -46.8852,
    director: "Lilian Rodrigues Paes",
    directorEmail: "lilian.rpaes@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Aracy da Silva P. Ferreira-Profª",
    phones: ["4162-1200", "4163-2287"],
    ramal: [],
    whatsapp: "(11) 4162-1200",
    address: "R. da Prata, 196",
    neighborhood: "Jardim Belval",
    latitude: -23.515,
    longitude: -46.876,
    director: "Cinthia Leite Barboza",
    directorEmail: "cinthia.barboza@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Armando Cavazza",
    phones: ["4168-4296", "4161-6045"],
    ramal: [],
    whatsapp: "(11) 4168-4296",
    address: "R. São Paulo, 706",
    neighborhood: "Engenho Novo",
    latitude: -23.5125,
    longitude: -46.8735,
    director: "Fernanda Aparecida Moreno Moreti",
    directorEmail: "fernanda.moreti@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Benedito Venâncio",
    phones: ["4198-7877", "4706-1052"],
    ramal: ["1450"],
    whatsapp: "(11) 4198-7877",
    address: "R. Vereador José Vieira, 116",
    neighborhood: "Jardim Regina Alice",
    latitude: -23.5235,
    longitude: -46.8845,
    director: "Patricia Cruz Ferreira da Silva",
    directorEmail: "patricia.silva@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Carlos Osmarinho de Lima - Prof. (Compl.)",
    phones: ["4163-4033"],
    ramal: [],
    whatsapp: "(11) 4163-4033",
    address: "Rua das Margaridas, 182",
    neighborhood: "Jardim Flórida",
    latitude: -23.5172,
    longitude: -46.8782,
    director: "Andrea da Cruz Silva",
    directorEmail: "andrea.csilva@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Décio Trujillo",
    phones: ["4194-1272", "4194-5381"],
    ramal: [],
    whatsapp: "(11) 4194-1272",
    address: "Estrada Velha de Itapevi, 3.860",
    neighborhood: "Vila Militar",
    latitude: -23.5355,
    longitude: -46.8965,
    director: "Silvia Ferreira Falcao",
    directorEmail: "silvia.falcao@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Eminoldo Harger",
    phones: ["4191-3572", "4688-1195"],
    ramal: [],
    whatsapp: "(11) 4191-3572",
    address: "Rua Padre Cicero Romão Batista, 75",
    neighborhood: "Parque Imperial",
    latitude: -23.5302,
    longitude: -46.8912,
  },
  {
    type: "EMEI",
    name: "Guilherme A. Siqueira- Cap.",
    phones: ["4168-1426"],
    ramal: [],
    whatsapp: "(11) 4168-1426",
    address: "Rua Dempachi Nakayama, 302",
    neighborhood: "Jardim Esperança",
    latitude: -23.5182,
    longitude: -46.8792,
    director: "Adriana de Toledo Sivieri",
    directorEmail: "adriana.sivieri@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "João Batista Pazinato Jr",
    phones: ["4191-3529", "4688-1222"],
    ramal: [],
    whatsapp: "(11) 4191-3529",
    address: "Rua Pará, 131",
    neighborhood: "Nova Aldeinha",
    latitude: -23.5335,
    longitude: -46.8945,
    director: "Eliane Pimentel Correia",
    directorEmail: "eliane.pimentel@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "João Evangelista de Oliveira",
    phones: ["4191-5865"],
    ramal: [],
    whatsapp: "(11) 4191-5865",
    address: "Rua Dom Feliciano, 240",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5212,
    longitude: -46.8822,
    director: "Juliana Rosa Lima",
    directorEmail: "juliana.lrima@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "João Fernandes",
    phones: ["4194-1273", "4201-7796"],
    ramal: [],
    whatsapp: "(11 ) 4201-7796",
    address: "R. Glória, 670",
    neighborhood: "Parque dos Camargos",
    latitude: -23.529,
    longitude: -46.89,
    director: "Viviane Marques de Silos Beguetto Rodrigues",
    directorEmail: "viviane.beguetto@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "José Oliveira da Silva - \"Seu Zequinha\"",
    phones: ["3164-1130"],
    ramal: [],
    whatsapp: "(11) 3164-1130",
    address: "Rua Terra, 326",
    neighborhood: "Jardim Tupanci",
    latitude: -23.5362,
    longitude: -46.8972,
    director: "Claudia Maria Rodrigues de Paula",
    directorEmail: "claudia.mpaula@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Lucineia de Oliveira",
    phones: ["4161-4866"],
    ramal: ["1600"],
    whatsapp: "(11) 4161-4866",
    address: "R. Doutor Parise, 120",
    neighborhood: "Vila Ceres",
    latitude: -23.5367,
    longitude: -46.8977,
    director: "Valterlene Martins",
    directorEmail: "valterlene.martins@professor.barueri.br",
  },
  {
    type: "EMEI",
    name: "Maria Meduneckas - Prof.ª (Complexo)",
    phones: ["4194-1274"],
    ramal: [],
    whatsapp: "(11) 98876-1714",
    address: "Av. Pres. Washington Luiz, 600",
    neighborhood: "Jardim Silveira",
    latitude: -23.5257,
    longitude: -46.8867,
    director: "Andrea Miguel Neves",
    directorEmail: "andrea.neves@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Maria Rosa Ferreira",
    phones: ["4193-2790", "4688-1221"],
    ramal: [],
    whatsapp: "(11) 4193-2790",
    address: "Rua Petrolina, 85",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5215,
    longitude: -46.8825,
  },
  {
    type: "EMEI",
    name: "Mário de L. C. da Silveira-Eng.",
    phones: ["4192-3200"],
    ramal: [],
    whatsapp: "(11) 4192-3200",
    address: "Av. Queimada, 505",
    neighborhood: "Res. Morada dos Lagos",
    latitude: -23.53,
    longitude: -46.891,
    director: "Eduardo Silva Coli",
    directorEmail: "eduardo.coli@educbarueri.sp.gov.br",
  },
  {
    type: "EMEI",
    name: "Sônia de M. P. C. Camargo-Profª",
    phones: ["4198-6362"],
    ramal: [],
    whatsapp: "(11) 4198-6362",
    address: "Rua Augusta, 198",
    neighborhood: "Jardim Maria Tereza",
    latitude: -23.4988136,
    longitude: -46.8732441,
    director: "Marisa Vilela Pinto",
    directorEmail: "marisa.vilela@professor.barueri.br",
  },
  {
    type: "EMMEI",
    name: "Emilia de Almeida - Prof.ª",
    phones: ["4198-9008", "4168-2085"],
    ramal: [],
    whatsapp: "(11 ) 4168-2085",
    address: "Rua Sumaré, 90",
    neighborhood: "Chácaras Marco",
    latitude: -23.5122,
    longitude: -46.8732,
    director: "Marcia do Carmo Dias",
    directorEmail: "marcia.dias@educbarueri.sp.gov.br",
  },
  {
    type: "EMMEI",
    name: "Irani dos Santos Cruz - Prof.ª",
    phones: ["4194-5264", "4194-5265"],
    ramal: [],
    whatsapp: "(11) 4194-5264",
    address: "Rua Mar Negro, 1.488",
    neighborhood: "Jardim Reginalice",
    latitude: -23.524,
    longitude: -46.885,
    director: "Cristiane Cordeiro Gomes",
    directorEmail: "cristiane.gomes@professor.barueri.br",
  },
  {
    type: "EMMEI",
    name: "Lauri de Castro",
    phones: ["4193-2740", "4193-2740"],
    ramal: [],
    whatsapp: "(11) 4193-2740",
    address: "R. Cândido Portinari, 40",
    neighborhood: "Vila São Silvestre",
    latitude: -23.537,
    longitude: -46.898,
    director: "Renata de S. Vianna Pinto",
    directorEmail: "renata.pinto@professor.barueri.br",
  },
  {
    type: "EMMEI",
    name: "Maria de Lourdes R. Lima - Prof.ª",
    phones: ["4198-4444", "4198-4445"],
    ramal: [],
    whatsapp: "(11) 4198-4445",
    address: "Rua Ilha Terceira, 207",
    neighborhood: "Parque Viana",
    latitude: -23.5365,
    longitude: -46.8975,
    director: "Marcos Antonio de Lima",
    directorEmail: "marcos.lima@professor.barueri.br",
  },
  {
    type: "EMMEI",
    name: "Silvio de Farias - Prof.",
    phones: ["4161-6022", "4161-6023"],
    ramal: [],
    whatsapp: "(11) 4161-6022",
    address: "Rua Ivani Maria Paes, 21",
    neighborhood: "Jardim dos Camargos",
    latitude: -23.5165,
    longitude: -46.8775,
    director: "Kelly Cristina Santos",
    directorEmail: "kelly.santos@professor.barueri.br",
  },
  {
    type: "EMMEI",
    name: "Teresa T. de A. A. N. Leite - Profª",
    phones: ["4194-5654", "4194-1598"],
    ramal: [],
    whatsapp: "(11) 4194-1598",
    address: "Rua da Prata, 196",
    neighborhood: "Jardim Belval",
    latitude: -23.5152,
    longitude: -46.8762,
    director: "Marilene Rodrigues C. dos Santos",
    directorEmail: "marilene.santos@educbarueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Aparecida Conceição S. Akyama (Inst. Verus)",
    phones: ["4163-6527"],
    ramal: [],
    whatsapp: null,
    address: "Av.Henrique Gonçalves Baptista, 1.796",
    neighborhood: "Jardim Itaquiti/Belval",
    latitude: -23.5157,
    longitude: -46.8767,
    director: "Aparecida de Fátima Madeira",
    directorEmail: "dir.osaparecidaakyama@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Aracy Martins de Lima (Inst. PROJAB)",
    phones: ["4375-4419", "4375-4420"],
    ramal: [],
    whatsapp: null,
    address: "Av.Henrique Gonçalves Baptista,453",
    neighborhood: "Jardim Belval",
    latitude: -23.5152,
    longitude: -46.8762,
    director: "Glaucimara dos Reis",
    directorEmail: "dir.osaracy@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Cleide Rodrigues Fagundes (Inst. Verus)",
    phones: ["4194-4941"],
    ramal: [],
    whatsapp: null,
    address: "Rua Nelly Masiero Fernandes, 55",
    neighborhood: "Recanto Phrynéa",
    latitude: -23.5322,
    longitude: -46.8932,
    director: "Maria de Jesus Nascimento",
    directorEmail: "dir.oscleiderodrigues@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Creche Santo Antônio (Inst. Verus)",
    phones: ["4163-1282"],
    ramal: [],
    whatsapp: null,
    address: "Rua Itapevi, 1.135",
    neighborhood: "Vila Engenho Novo",
    latitude: null,
    longitude: null,
    director: "Flavia Cristina Paiva da Silva",
    directorEmail: "dir.oscrechesantoantonio@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Dona Leonor de A. M. do Prado (Inst. CEDECC)",
    phones: ["4194-4941", "4194-4941"],
    ramal: [],
    whatsapp: null,
    address: "R. Cap. Anacleto, 137",
    neighborhood: "Centro",
    latitude: -23.5135,
    longitude: -46.8745,
    director: "Maria de Fátima do N. da Cunha",
    directorEmail: "dir.osdleonor@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Edgard S. Pereira (Instituto CEDECC)",
    phones: ["4161-5544", "4161-5588"],
    ramal: [],
    whatsapp: null,
    address: "Rua Augusta, 198",
    neighborhood: "Jardim Maria Tereza",
    latitude: -23.4988136,
    longitude: -46.8732441,
    director: "Daniele Gomes Pereira",
    directorEmail: "dir.osedgardspereira@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Izabel M. S. de Oliveira (Inst. Barueri)",
    phones: ["4201-2090", "4201-2091"],
    ramal: [],
    whatsapp: null,
    address: "Rua Maria de Fátima, 81",
    neighborhood: "Jardim Esperança",
    latitude: null,
    longitude: null,
    director: "Marta Helena da Silva",
    directorEmail: "dir.osizabel@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "João de Deus (Inst. Verus)",
    phones: ["4191-2364", "4168-3560"],
    ramal: [],
    whatsapp: null,
    address: "R. Renilde de Almeida, 400",
    neighborhood: "Parque Imperial",
    latitude: -23.531,
    longitude: -46.892,
    director: "Maria Helena de Morais",
    directorEmail: "dir.osjoaodeus@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "João Gonçalves de Lima",
    phones: ["4198-4906"],
    ramal: [],
    whatsapp: null,
    address: "Rua Augusta, 198",
    neighborhood: "Jardim Maria Tereza",
    latitude: -23.4988136,
    longitude: -46.8732441,
    director: "Valterlene Martins",
    directorEmail: "dir.osjoao-glima@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "João da C. Lima (Inst. Betel)",
    phones: ["4168-3642", "4168-3643"],
    ramal: [],
    whatsapp: null,
    address: "Rua Nova Aurora, 160",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5217,
    longitude: -46.8827,
    director: "Isabel Cristina de Souza",
    directorEmail: "dir.osjoaodc@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Joana A. M. da Silva (Inst. PROJAB)",
    phones: ["4163-4700", "4163-4700"],
    ramal: [],
    whatsapp: null,
    address: "Rua do Pássaro, 27",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.5355,
    longitude: -46.8965,
    director: "Lia Marcia da Silva",
    directorEmail: "dir.osjoanadam@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "João da C. Lima (Inst. Betel)",
    phones: ["4168-3642", "4168-3643"],
    ramal: [],
    whatsapp: null,
    address: "Rua Nova Aurora, 160",
    neighborhood: "Jardim Mutinga",
    latitude: -23.5217,
    longitude: -46.8827,
  },
  {
    type: "OS",
    name: "Joana A. M. da Silva (Inst. PROJAB)",
    phones: ["4163-4700", "4163-4700"],
    ramal: [],
    whatsapp: null,
    address: "Rua do Pássaro, 27",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.5355,
    longitude: -46.8965,
  },
  {
    type: "OS",
    name: "João de Deus (Inst. Verus)",
    phones: ["4191-2364", "4168-3560"],
    ramal: [],
    whatsapp: null,
    address: "R. Renilde de Almeida, 400",
    neighborhood: "Parque Imperial",
    latitude: -23.531,
    longitude: -46.892,
  },
  {
    type: "OS",
    name: "João Gonçalves de Lima",
    phones: ["4198-4906"],
    ramal: [],
    whatsapp: null,
    address: "Rua Augusta, 198",
    neighborhood: "Jardim Maria Tereza",
    latitude: -23.4988136,
    longitude: -46.8732441,
  },
  {
    type: "OS",
    name: "Jurema V. de M. Lira (Inst. CEDECC)",
    phones: ["4194-0194", "97968-8260"],
    ramal: [],
    whatsapp: null,
    address: "Av. Exército Brasileiro, 1000",
    neighborhood: "Jardim Tupã",
    latitude: -23.5357,
    longitude: -46.8967,
    director: "Maria do Carmo Souza Pereira",
    directorEmail: "dir.osjurema@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Maria da Silva Camargo (Inst. Verus)",
    phones: ["4168-2088", "4168-2089"],
    ramal: [],
    whatsapp: null,
    address: "R. da Prata, 204",
    neighborhood: "Jardim Belval",
    latitude: -23.5155,
    longitude: -46.8765,
    director: "Maria Lúcia da Silva",
    directorEmail: "dir.osmdsilvacamargo@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Marisa Odaine de O. Molina (Instituto CEDECC)",
    phones: ["4162-1970", "4162-2112"],
    ramal: [],
    whatsapp: null,
    address: "Rua Dr. Fernando O. Santos, 410",
    neighborhood: "Vila Engenho Novo",
    latitude: -23.5352,
    longitude: -46.8962,
    director: "Rosemari Vilela",
    directorEmail: "dir.osmarisa@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Nelson Marques (Inst. PROJAB)",
    phones: ["4191-1709", "4195-4337"],
    ramal: [],
    whatsapp: null,
    address: "Rua Otacílio Alves Martins, 75",
    neighborhood: "Parque Imperial",
    latitude: -23.5312,
    longitude: -46.8922,
    director: "Cibele da Silva Castelhano",
    directorEmail: "dir.osnelson@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Roberto Griti Medeiros (Inst. Alcançando Vidas)",
    phones: ["4552-7012", "4552-7028"],
    ramal: [],
    whatsapp: null,
    address: "Rua Niterói - 195",
    neighborhood: "Jardim Maria Helena",
    latitude: -23.5195,
    longitude: -46.8805,
    director: "Renata Gomes Mendonça",
    directorEmail: "dir.osrobertogriti@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Tadataka Ito - \"Mário Ito\" (Inst. Barueri)",
    phones: ["4194-0194", "97968-8260"],
    ramal: [],
    whatsapp: null,
    address: "Avenida Exército Brasileiro, 1000",
    neighborhood: "Jardim Tupã",
    latitude: -23.5357,
    longitude: -46.8967,
    director: "Maria do Carmo Souza Pereira",
    directorEmail: "dir.osmarioito@educacao.barueri.sp.gov.br",
  },
  {
    type: "OS",
    name: "Valdinéia de Fátima Cassoli (Inst. Alvorada)",
    phones: ["4706-1671"],
    ramal: [],
    whatsapp: null,
    address: "Rua Duque de Caxias, 150",
    neighborhood: "Vila Engenho Novo",
    latitude: null,
    longitude: null,
    director: "Márcia Lúcia Leite Bortolozi",
    directorEmail: "dir.osvaldineiacassoli@educacao.barueri.br",
  },
  {
    type: "OS",
    name: "Wandeir Ribeiro (Inst. Verus)",
    phones: ["4168-3111", "4168-3112"],
    ramal: [],
    whatsapp: null,
    address: "Av. dos Coqueiros, 290",
    neighborhood: "Vila Nova",
    latitude: null,
    longitude: null,
    director: "Claudia Regina de Oliveira",
    directorEmail: "dir.oswandeir@educacao.barueri.sp.gov.br",
  },
];